from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path("unit-reference/", views.unit_reference, name="unit_reference"),
    path(
        "unit-converter/",
        views.unit_converter,
        name="unit_converter"
    ),
    path(
        'underground-withdrawal/',
        views.underground_withdrawal,
        name='underground_withdrawal'
    ),
    path(
        "oil-expansion/",
        views.oil_expansion,
        name="oil_expansion"
    ),
    path(
        "gas-cap-expansion/",
        views.gas_cap_expansion,
        name="gas_cap_expansion"
    ),
    path(
        "formation-water-expansion/",
        views.formation_water_expansion,
        name="formation_water_expansion"
    ),
    path(
        "general-mbe/",
        views.general_mbe,
        name="general_mbe"
    ),
    path(
        "gas-fvf/",
        views.gas_fvf,
        name="gas_fvf"
    ),
    path(
        "gas-cap-ratio/",
        views.gas_cap_ratio,
        name="gas_cap_ratio"
    ),
    path(
        "recovery-factor/",
        views.recovery_factor,
        name="recovery_factor"
    ),
    path(
        "ogip/",
        views.ogip,
        name="ogip"
    ),
    path(
        "schilthuis/",
        views.schilthuis_water_influx,
        name="schilthuis"
    ),
    path(
        "van-everdingen-hurst/",
        views.van_everdingen_hurst,
        name="van_everdingen_hurst"
    ),
    path(
        "fetkovich/",
        views.fetkovich_water_influx,
        name="fetkovich"
    ),
    path(
        "gas-material-balance/",
        views.gas_material_balance,
        name="gas_material_balance"
    ),
    path(
        "volumetric-oil-reservoir/",
        views.volumetric_oil_reservoir,
        name="volumetric_oil_reservoir"
    ),
    path(
        "gas-cap-drive-reservoir/",
        views.gas_cap_drive_reservoir,
        name="gas_cap_drive_reservoir"
    ),
    path(
        "water-drive-reservoir/",
        views.water_drive_reservoir,
        name="water_drive_reservoir"
    ),
    path(
        "combination-drive-reservoir/",
        views.combination_drive_reservoir,
        name="combination_drive_reservoir"
    ),
    path(
        "oil-expansion-term/",
        views.oil_expansion_term,
        name="oil_expansion_term"
    ),
    path(
        "oil-fvf/",
        views.oil_fvf,
        name="oil_fvf"
    ),
    path(
        "unit-converter/",
        views.unit_converter,
        name="unit_converter"
    ),
]